// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC67txZNZdLP5bQdyjrmRqt3Z-hyoJVhog',
    appId: '1:271243528011:web:5cd6f2239fc1716fb34ace',
    messagingSenderId: '271243528011',
    projectId: 'sigaunmucol',
    authDomain: 'sigaunmucol.firebaseapp.com',
    storageBucket: 'sigaunmucol.firebasestorage.app',
    measurementId: 'G-TECT07XE24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vSnvFTAbspFCmjcZp997oCFE0PAJ_3A',
    appId: '1:271243528011:android:dc0aaf2f5a0eb788b34ace',
    messagingSenderId: '271243528011',
    projectId: 'sigaunmucol',
    storageBucket: 'sigaunmucol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdL3pq_h5c7iwK0rxvn5iv9h2X8aJbf38',
    appId: '1:271243528011:ios:c1597c635813f64eb34ace',
    messagingSenderId: '271243528011',
    projectId: 'sigaunmucol',
    storageBucket: 'sigaunmucol.firebasestorage.app',
    iosBundleId: 'com.example.sigaUnmucol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdL3pq_h5c7iwK0rxvn5iv9h2X8aJbf38',
    appId: '1:271243528011:ios:c1597c635813f64eb34ace',
    messagingSenderId: '271243528011',
    projectId: 'sigaunmucol',
    storageBucket: 'sigaunmucol.firebasestorage.app',
    iosBundleId: 'com.example.sigaUnmucol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC67txZNZdLP5bQdyjrmRqt3Z-hyoJVhog',
    appId: '1:271243528011:web:be08a0d949fa490db34ace',
    messagingSenderId: '271243528011',
    projectId: 'sigaunmucol',
    authDomain: 'sigaunmucol.firebaseapp.com',
    storageBucket: 'sigaunmucol.firebasestorage.app',
    measurementId: 'G-9W10YC81DF',
  );
}
